# GitHub Pages-compatible html-proofer config
# Avoid crawling archived snapshots and their assets.
assume_extension: true
disable_external: true
ignore_urls:
  - %r{^/archive/}
ignore_files:
  - %r{^./_site/(archive|_site-archive)/}
